# Default values for external-dns-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: external-dns
namespace: kube-system

domainFilter: gigantic.io
provider: azure

sources:
  - service
  # Disable ingress source by default.
  # - ingress

metricsPort: 10254
priviligedPspRoleName: privileged-psp-user

image:
  repository: quay.io/giantswarm/external-dns
  tag: v0.5.2-3-g6c05028

resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi
